version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:lint
      - run: npm run test

  deploy:
    docker:
      - image: nikolaik/python-nodejs:python3.7-nodejs10
    working_directory: ~/repo
    steps:
      - checkout
      - run: pip install awscli
      - run: pip install aws-sam-cli
      - run: npm ci
      - run: npm run package
      - run: npm run publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: deploy

  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: deploy
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: deploy
